name: Deploy on release

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Dockerfile for backend
        run: docker build -f Dockerfile.backend --tag arnu515/workshift-backend:${{ github.ref_name || github.commit_sha || 'latest' }} .

      - name: Login to dockerhub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PW }}
      
      - name: Push to dockerhub
        run: docker push arnu515/workshift-backend:${{ github.ref_name || github.commit_sha || 'latest' }}
      
      - name: Configure SSh
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/workshift-backend-key
          chmod 600 ~/.ssh/workshift-backend-key
          cat >> ~/.ssh/config <<END
          HOST workshift-backend
            Hostname $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/workshfit-backend-key
            StrictHostKeyChecking no
          END
      
      - name: SSH - Run deploy script
        run: "ssh workshift-backend '~/deploy-workshift-backend.sh arnu515/workshift-backend:${{ github.ref_name || github.commit_sha || 'latest' }}'"
      
